app:
  api_file: "api/api.yml"
  port: 8080
redis:
  host: "redis_map"
  port: 6379
  db: 0
  data_prefix: "ipvisualizator"
users:
# UIDs of users described in this config must be less than 1000
- uid: 1
  username: "admin"
  admin: true
  authorization: "ce7f5abdf69365fcdd9703009e54d2de"
